// Package compose generates a docker-compose.yml containing only the
// services a workflow actually needs, plus the runtime itself built with
// only the modules it uses.
package compose

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mrjvadi/tgcreator/internal/workflow"
)

type Options struct {
	WorkflowFile string // path of the workflow next to the compose file
	Image        string // runtime image; ignored when BuildContext is set
	BuildContext string // build the runtime from source (path to repo)
	Project      string
	ExtraMounts  []string // e.g. "./assets:/app/assets:ro"
}

// Generate renders docker-compose YAML for wf with the given requirements
// (engine.Requirements()).
func Generate(wf *workflow.Workflow, requires []string, opt Options) (string, error) {
	if opt.WorkflowFile == "" {
		opt.WorkflowFile = "./workflow.json"
	}
	if opt.Image == "" {
		opt.Image = "tgcreator:latest"
	}

	needRedis := false
	var dbs []string
	for _, r := range requires {
		switch {
		case r == "redis":
			needRedis = true
		case strings.HasPrefix(r, "db:"):
			dbs = append(dbs, strings.TrimPrefix(r, "db:"))
		}
	}
	sort.Strings(dbs)

	var (
		services []string
		volumes  []string
		env      = map[string]string{"TGC_BOT_TOKEN": "${BOT_TOKEN:?set BOT_TOKEN in .env}"}
		deps     []string
		drivers  = map[string]bool{}
		mounts   = append([]string{opt.WorkflowFile + ":/app/workflow.json:ro"}, opt.ExtraMounts...)
	)

	if needRedis {
		img := "redis:7-alpine"
		if wf.Services.Redis != nil && wf.Services.Redis.Image != "" {
			img = wf.Services.Redis.Image
		}
		services = append(services, fmt.Sprintf(`  redis:
    image: %s
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
`, img))
		volumes = append(volumes, "redis-data")
		env["TGC_REDIS_URL"] = "redis://redis:6379/0"
		deps = append(deps, "redis")
	}

	for _, name := range dbs {
		db, ok := wf.Services.Databases[name]
		if !ok {
			return "", fmt.Errorf("workflow uses database %q but services.databases.%s is missing", name, name)
		}
		drivers[db.Driver] = true
		svc := "db-" + sanitize(name)
		dsnEnv := workflow.DSNEnv(name)
		switch db.Driver {
		case "postgres":
			img := orDefault(db.Image, "postgres:16-alpine")
			services = append(services, fmt.Sprintf(`  %[1]s:
    image: %[2]s
    restart: unless-stopped
    environment:
      POSTGRES_USER: tgc
      POSTGRES_PASSWORD: ${DB_PASSWORD:-tgc}
      POSTGRES_DB: %[3]s
    volumes:
      - %[1]s-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tgc -d %[3]s"]
      interval: 5s
      timeout: 3s
      retries: 20
`, svc, img, sanitize(name)))
			env[dsnEnv] = fmt.Sprintf("postgres://tgc:${DB_PASSWORD:-tgc}@%s:5432/%s?sslmode=disable", svc, sanitize(name))
			volumes = append(volumes, svc+"-data")
			deps = append(deps, svc)
		case "mysql":
			img := orDefault(db.Image, "mysql:8.4")
			services = append(services, fmt.Sprintf(`  %[1]s:
    image: %[2]s
    restart: unless-stopped
    environment:
      MYSQL_USER: tgc
      MYSQL_PASSWORD: ${DB_PASSWORD:-tgc}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-tgc-root}
      MYSQL_DATABASE: %[3]s
    volumes:
      - %[1]s-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-utgc", "-p${DB_PASSWORD:-tgc}"]
      interval: 5s
      timeout: 3s
      retries: 30
`, svc, img, sanitize(name)))
			env[dsnEnv] = fmt.Sprintf("tgc:${DB_PASSWORD:-tgc}@tcp(%s:3306)/%s?parseTime=true", svc, sanitize(name))
			volumes = append(volumes, svc+"-data")
			deps = append(deps, svc)
		case "sqlite":
			env[dsnEnv] = "file:/data/" + sanitize(name) + ".db?_pragma=journal_mode(WAL)"
			if !contains(mounts, "tgc-data:/data") {
				mounts = append(mounts, "tgc-data:/data")
				volumes = append(volumes, "tgc-data")
			}
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by `tgcreator compose` for workflow: " + wf.Name + "\n")
	b.WriteString("# Only the services this workflow uses are included.\n")
	if opt.Project != "" {
		b.WriteString("name: " + opt.Project + "\n")
	}
	b.WriteString("services:\n  bot:\n")
	if opt.BuildContext != "" {
		b.WriteString("    build:\n      context: " + opt.BuildContext + "\n")
		b.WriteString("      args:\n        TAGS: \"" + BuildTags(needRedis, drivers) + "\"\n")
		b.WriteString("    image: " + opt.Image + "\n")
	} else {
		b.WriteString("    image: " + opt.Image + "\n")
	}
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    command: [\"run\", \"-w\", \"/app/workflow.json\"]\n")
	b.WriteString("    environment:\n")
	for _, k := range sortedKeys(env) {
		fmt.Fprintf(&b, "      %s: %q\n", k, env[k])
	}
	b.WriteString("    volumes:\n")
	for _, m := range mounts {
		b.WriteString("      - " + m + "\n")
	}
	if wf.Bot.Mode == "webhook" {
		listen := orDefault(wf.Bot.Webhook.Listen, ":8080")
		port := listen[strings.LastIndex(listen, ":")+1:]
		b.WriteString("    ports:\n      - \"" + port + ":" + port + "\"\n")
	}
	if len(deps) > 0 {
		b.WriteString("    depends_on:\n")
		for _, d := range deps {
			b.WriteString("      " + d + ":\n        condition: service_healthy\n")
		}
	}
	for _, s := range services {
		b.WriteString("\n")
		b.WriteString(s)
	}
	if len(volumes) > 0 {
		b.WriteString("\nvolumes:\n")
		for _, v := range volumes {
			b.WriteString("  " + v + ":\n")
		}
	}
	return b.String(), nil
}

// BuildTags returns the Go build tags that drop unused modules from the
// runtime binary.
func BuildTags(redis bool, drivers map[string]bool) string {
	var tags []string
	if !redis {
		tags = append(tags, "no_redis")
	}
	if !drivers["postgres"] {
		tags = append(tags, "no_postgres")
	}
	if !drivers["mysql"] {
		tags = append(tags, "no_mysql")
	}
	if drivers["sqlite"] {
		tags = append(tags, "sqlite")
	}
	return strings.Join(tags, " ")
}

func sanitize(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
